export const ROCKETS_ARE_LOADING = 'ROCKETS_ARE_LOADING';
export const ROCKETS_FAILED_TO_LOAD = 'ROCKETS_FAILED_TO_LOAD';

export const ROCKET_ARE_LOADING = 'ROCKET_ARE_LOADING';
export const ROCKET_FAILED_TO_LOAD = 'ROCKET_FAILED_TO_LOAD';

export const ROCKETS_ARE_LOADING_BY_FILTER = 'ROCKETS_ARE_LOADING_BY_FILTER';
export const ROCKETS_FAILED_TO_LOAD_BY_FILTER = 'ROCKETS_FAILED_TO_LOAD_BY_FILTER';
